/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import code.HashTable;
import code.Data;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */

public class TabelData extends javax.swing.JFrame {

    DefaultTableModel model;
    public static HashTable hash;
    /**
     * Creates new form admin
     */
    public TabelData() {
        initComponents();
        hash = new HashTable();     
         tableModel();
       
       
    }

     public void add() {
        if ("".equals(fieldNama.getText()) || "".equals(fieldNIK.getText()) || "".equals(fieldTanggal.getText()) || "" .equals(fieldSatuan.getText())) {
        } else {
            long NIK = Long.parseLong(fieldNIK.getText());
            String Nama = fieldNama.getText();
            String Tanggal = fieldTanggal.getText();
            String Tujuan = cmbKategori.getSelectedItem().toString();
            String Kategori = cmbKategori.getSelectedItem().toString();
            String Satuan = fieldSatuan.getText();

            hash.insertGUI(NIK, Nama, Tanggal, Tujuan, Kategori, Satuan);
            clear();
            fieldNIK.requestFocus();
        }
    }
    
    public void updateData() {
        if ("".equals(fieldNama.getText()) || "".equals(fieldNIK.getText()) || "".equals(fieldTanggal.getText()) || "" .equals(fieldSatuan.getText())) {
        } else {
            long NIK = Long.parseLong(fieldNIK.getText());
            String Nama = fieldNama.getText();
            String Tanggal = fieldTanggal.getText();
            String Tujuan = cmbKategori.getSelectedItem().toString();
            String Kategori = cmbKategori.getSelectedItem().toString();
            String Satuan = fieldSatuan.getText();
           
            hash.deleteSelected(Long.parseLong(fieldSearch.getText()));
            hash.updateAt(NIK, Nama, Tanggal, Tujuan, Kategori, Satuan);

            clear();
            fieldNIK.requestFocus();
        }
    }

    public void clear() {
        fieldNIK.setText("");
        fieldNama.setText("");
        fieldTanggal.setText("");
        cmbKategori.setSelectedItem(0);
        cmbKategori.setSelectedItem(0);
        fieldSatuan.setText("");
        btnSimpan.setEnabled(true);
    }

    public void tableModel() {
        DefaultTableModel model = (DefaultTableModel) jTableOutput.getModel();
        model.setRowCount(0);
        String[][] res = hash.readData();
        for (int i = 0; i < res.length; i++) {
            Object[] row = {res[i][0], res[i][1], res[i][2], res[i][3], res[i][4],res[i][5]};
            model.addRow(row);
        }
    }

    private void findDataByNIK(long input) {
        Data found = hash.find(input);
        if (found != null) {
            DefaultTableModel model = (DefaultTableModel) jTableOutput.getModel();
            model.setRowCount(0);
            Object[] row = {found.getNIK(), found.getNama(), found.getTanggal(), found.getTujuan(), found.getKategori(), found.getSatuan()};
            model.addRow(row);
            fieldNIK.setText(Long.toString(found.getNIK()));
            fieldNama.setText(found.getNama());
            fieldTanggal.setText(found.getTanggal());
            String Tujuan = found.getTujuan();
            if (Tujuan.equals("Palu")) {
                cmbKategori.setSelectedIndex(1);
            } else {
                cmbKategori.setSelectedIndex(0);
            }
            String Kategori = found.getKategori();
            if (Kategori.equals("Uang")) {
                cmbKategori.setSelectedIndex(1);
            } else {
                cmbKategori.setSelectedIndex(0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Maaf, Data dengan NIK " + input + " tidak bisa ditemukan");
        }
    }
    
    public void Delete() {
        try {
            hash.deleteSelected(Long.parseLong(fieldSearch.getText()));
            JOptionPane.showMessageDialog(null, fieldSearch.getText() + " Deleted");
        } catch (Exception e) {
            System.out.println("Gagal Menghapus");
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        fieldNIK = new javax.swing.JTextField();
        fieldTanggal = new javax.swing.JTextField();
        fieldSatuan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        cmbKategori = new javax.swing.JComboBox<>();
        cmbTujuan = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOutput = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fieldSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Miriam Fixed", 1, 24)); // NOI18N
        jLabel11.setText("DONASI");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(240, 10, 140, 30);

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel12.setText("Admin :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 10, 60, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 20, 620, 50);

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Satuan");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 270, 120, 30);

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIK");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 10, 120, 30);

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kategori");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 230, 120, 30);

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tujuan");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 180, 120, 30);

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Donatur ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 70, 120, 30);

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 120, 120, 30);

        fieldNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldNamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldNamaKeyTyped(evt);
            }
        });
        jPanel3.add(fieldNama);
        fieldNama.setBounds(170, 70, 410, 30);

        fieldNIK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldNIKKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldNIKKeyTyped(evt);
            }
        });
        jPanel3.add(fieldNIK);
        fieldNIK.setBounds(170, 10, 410, 30);

        fieldTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldTanggalKeyTyped(evt);
            }
        });
        jPanel3.add(fieldTanggal);
        fieldTanggal.setBounds(170, 130, 410, 30);
        jPanel3.add(fieldSatuan);
        fieldSatuan.setBounds(170, 270, 410, 30);

        btnSimpan.setBackground(new java.awt.Color(204, 204, 204));
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan);
        btnSimpan.setBounds(590, 10, 90, 25);

        ubah.setBackground(new java.awt.Color(204, 204, 204));
        ubah.setText("Edit");
        ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahMouseClicked(evt);
            }
        });
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel3.add(ubah);
        ubah.setBounds(590, 50, 90, 25);

        bersihkan.setBackground(new java.awt.Color(204, 204, 204));
        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });
        jPanel3.add(bersihkan);
        bersihkan.setBounds(590, 90, 90, 25);

        hapus.setBackground(new java.awt.Color(204, 204, 204));
        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel3.add(hapus);
        hapus.setBounds(590, 130, 90, 25);

        keluar.setBackground(new java.awt.Color(204, 204, 204));
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel3.add(keluar);
        keluar.setBounds(590, 170, 90, 25);

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barang", "Uang", "Bahan Pokok", " " }));
        jPanel3.add(cmbKategori);
        cmbKategori.setBounds(170, 230, 170, 30);

        cmbTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Palu", "Papua" }));
        cmbTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTujuanActionPerformed(evt);
            }
        });
        jPanel3.add(cmbTujuan);
        cmbTujuan.setBounds(170, 180, 170, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(40, 80, 690, 310);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(null);

        jTableOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIK", "Nama", "Tanggal", "Tujuan", "Kategori", "Satuan"
            }
        ));
        jTableOutput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOutputMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOutput);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(40, 60, 650, 120);

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pencarian Menurut Kategori");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 10, 210, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Refresh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(270, 20, 90, 25);

        fieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldSearchKeyTyped(evt);
            }
        });
        jPanel2.add(fieldSearch);
        fieldSearch.setBounds(390, 20, 170, 30);

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch);
        btnSearch.setBounds(600, 20, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 400, 740, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Hak-hak-anak-yang-wajib-dipenuhi.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        setBounds(0, 0, 836, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_bersihkanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNamaKeyTyped
        // TODO add your handling code here:
          char enter = evt.getKeyChar();
        if (Character.isDigit(enter)) {//Agar yang diinput hanya huruf dan karakter
            evt.consume(); //Mematikan keyboard angka
        }
        if (fieldNama.getText().length() == 30) { //Memberikan batasan
            evt.consume(); //Mematikan keyboard ketika sudah sampai batasnya
        }
    }//GEN-LAST:event_fieldNamaKeyTyped

    private void fieldNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNamaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaKeyPressed

    private void fieldNIKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNIKKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            fieldNama.requestFocus();
        }
    }//GEN-LAST:event_fieldNIKKeyPressed

    private void fieldNIKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNIKKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) { //Agar yang diinput hanya angka
            evt.consume(); //Mematikan keyboard huruf
        }
        if (fieldNIK.getText().length() == 20) { //Memberikan batasan inputan
            evt.consume(); //Mematikan keyboard ketika sudah sampai batasnya
        }
    }//GEN-LAST:event_fieldNIKKeyTyped

    private void fieldTanggalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTanggalKeyTyped
        // TODO add your handling code here:
         char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) { //Agar yang diinput hanya angka
           // evt.consume(); //Mematikan keyboard huruf
        }
        if (fieldTanggal.getText().length() == 13) { //Memberikan batasan inputan
            evt.consume(); //Mematikan keyboard ketika sudah sampai batasnya
        }
    }//GEN-LAST:event_fieldTanggalKeyTyped

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        findDataByNIK(Long.parseLong(fieldSearch.getText()));
    }//GEN-LAST:event_btnSearchMouseClicked

    private void fieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSearchKeyTyped
        // TODO add your handling code here:
         if (fieldSearch.getText().equals("")) {
            btnSimpan.setEnabled(true);
        } else {
            btnSimpan.setEnabled(false);
        }
    }//GEN-LAST:event_fieldSearchKeyTyped

    private void fieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSearchKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("".equals(fieldSearch.getText())) {
                JOptionPane.showMessageDialog(null, "Field pencarian Kosong");
            } else {
                findDataByNIK(Long.parseLong(fieldSearch.getText()));
            }
        }
    }//GEN-LAST:event_fieldSearchKeyPressed

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        if ("".equals(fieldSearch.getText())) {
            JOptionPane.showMessageDialog(null, "Field Pencarian Kosong");
        } else {
            Delete();
            tableModel();
            clear();
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
         add();
        tableModel();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseClicked
        // TODO add your handling code here:
         if (fieldSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Field Pencarian Kosong");
        } else if (fieldNIK.getText().equals("") || fieldNama.getText().equals("") || fieldTanggal.getText().equals("") || fieldSatuan.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Semua Kolom Harus Diisi");
            return;
        } else {
            updateData();
            tableModel();
            clear();
            fieldNIK.requestFocus();
        }
    }//GEN-LAST:event_ubahMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        clear();
        tableModel();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTableOutputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOutputMouseClicked
        // TODO add your handling code here:
         int i = jTableOutput.getSelectedRow();
        if (i > -1) {
            fieldNIK.setText(model.getValueAt(i, 0).toString());
            fieldNama.setText(model.getValueAt(i, 1).toString());
            fieldTanggal.setText(model.getValueAt(i, 2).toString());
            cmbTujuan.setSelectedItem(model.getValueAt(i, 3).toString());
            cmbKategori.setSelectedItem(model.getValueAt(i, 4).toString());
            fieldSatuan.setText(model.getValueAt(i, 5).toString());
        }
    }//GEN-LAST:event_jTableOutputMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cmbTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTujuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkan;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbTujuan;
    private javax.swing.JTextField fieldNIK;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldSatuan;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JTextField fieldTanggal;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOutput;
    private javax.swing.JButton keluar;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

     

    
}